language: java
jdk:
  - oraclejdk8

before_script: 
- git submodule update
- ./build contrib
script: 
- ./build compile
- ls -lah /home/travis/build/AnyChart/ACDVF/out/

after_success:
- echo -e "Host static.anychart.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh root@static.anychart.com "mkdir -p /apps/static/js/$TRAVIS_BRANCH"
- git rev-parse HEAD >> ./out/commit-hash.txt
- scp /home/travis/build/AnyChart/ACDVF/out/anychart-bundle.min.js root@static.anychart.com:/apps/static/js/$TRAVIS_BRANCH/anychart-bundle.min.js
- scp /home/travis/build/AnyChart/ACDVF/out/anychart-ui.min.css root@static.anychart.com:/apps/static/css/$TRAVIS_BRANCH/anychart-ui.min.css
- scp /home/travis/build/AnyChart/ACDVF/out/commit-hash.txt root@static.anychart.com:/apps/static/js/$TRAVIS_BRANCH/commit-hash.txt

notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
  webhooks:
    - https://integram.org/hkwgksh3usqogp7j4
