language: java
sudo: false
jdk:
  - oraclejdk8

before_script: ./build contrib
script: ./build compile

after_success:
- echo -e "Host static.anychart.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh root@static.anychart.com "mkdir -p /apps/static/js/$TRAVIS_BRANCH"
- scp out/anychart-bundle.min.js root@static.anychart.com:/apps/static/js/$TRAVIS_BRANCH/anychart-bundle.min.js

notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
